/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-qWVRO0HcMT45kHHhm1Qj-j2ys2GuSQ6AaIK8xB6urJy3zRUFwii0DAIL83A-LHFew16vnOd5g5iY2imbLE9yqga61Wn2ZK8XCnQCTC-IxSQP9FzoTNHiMdHo",
  "tt": "tt-1-OXwNhQvbHrMA2RDpbKw8ufxTXpOJ74Hee-tAnIjNdNM=",
  "version": "2020-11-20"
}

export default ebconfig;