/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-KeCRcwehT9MuCkkP0EaqTTeYqu3ey2mIIbcS1-p3RopQ8gP-uIvsvdbJZmpw2a5ZlwHyVCG6hGSQYAkMrilj5HJlo7k8PHnbv1iPv5WkOGZbaaD03saRuaZq",
  "tt": "tt-1-troxIVyYS9stTgoeraFjEPy-jasJLx1x1jZnioPWIeY=",
  "version": "2020-11-20"
}

export default ebconfig;